//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CHTGL.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CHTGL_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAIN                   129
#define IDD_SYS_DLG                     130
#define IDD_ADDKF                       131
#define IDD_ADDQWR                      131
#define IDD_ADDHT_DLG                   132
#define IDD_ADDCUSTOMER                 133
#define IDD_YUJING_DLG                  134
#define IDD_SELECTHT_DLG                137
#define IDD_DLG_SHT                     138
#define IDD_ADDSFK_DLG                  139
#define IDD_DLG_KPGL                    140
#define IDB_BMP_LOGINBK                 141
#define IDB_BMP_JBXX                    142
#define IDB_BMP_HTGL                    143
#define IDB_BMP_WLGL                    144
#define IDB_BMP_YJSX                    145
#define IDB_BMP_KPGL                    146
#define IDB_BMP_TCGL                    147
#define IDD_DLG_BTN                     148
#define IDB_BMP_BQYR                    149
#define IDB_BMP_BGYS                    150
#define IDB_BMP_BKFGL                   151
#define IDB_BMP_HTGL_S                  152
#define IDB_BMP_HTGL_A                  153
#define IDB_BMP_HTGL_D                  154
#define IDD_DLG_TCGL                    155
#define IDB_BMP_QRCODE                  156
#define IDD_DLG_TCGLAddByHT             157
#define IDC_STATIC_WND                  1000
#define IDC_EDIT_SKLX                   1001
#define IDC_LIST_SKLX                   1002
#define IDC_BTN_SKLXSAVE                1003
#define IDC_BTN_SKLXDEL                 1004
#define IDC_COMBO_KFLX                  1005
#define IDC_COMBO2                      1006
#define IDC_COMBO_QWR                   1006
#define IDC_COMBO_KFMC                  1007
#define IDC_COMBO4                      1008
#define IDC_COMBO_SFKMC                 1008
#define IDC_DATETIMEPICKER1             1009
#define IDC_DATETIMEPICKER2             1010
#define IDC_EDIT1                       1011
#define IDC_EDIT2                       1012
#define IDC_LIST_SFKTJ                  1013
#define IDC_EDIT5                       1013
#define IDC_BTN_ADDTJ                   1014
#define IDC_LIST_KPMX                   1014
#define IDC_EDIT_SJJR                   1014
#define IDC_EDIT_HKJR                   1014
#define IDC_BTN_DELTJ                   1015
#define IDC_EDIT_KP3                    1015
#define IDC_EDIT_BL                     1015
#define IDC_EDIT3                       1016
#define IDC_EDIT_XMMS                   1016
#define IDC_EDIT_YH                     1016
#define IDC_EDIT_FPHM                   1016
#define IDC_EDIT_KT                     1016
#define IDC_EDIT4                       1017
#define IDC_EDIT_BZ                     1017
#define IDC_EDIT_KPMONEY                1017
#define IDC_EDIT_YT                     1017
#define IDC_BTN_ADDHT                   1018
#define IDC_EDIT_WT                     1018
#define IDC_BTN_ADD                     1019
#define IDC_EDIT_TCMoney                1019
#define IDC_STATIC_NAME                 1020
#define IDC_BTN_DEL                     1021
#define IDC_LIST_KFZL                   1022
#define IDC_LIST_QWR                    1023
#define IDC_BTN_SAVE                    1024
#define IDC_EDIT_NAME                   1025
#define IDC_EDIT_SFZ                    1026
#define IDC_EDIT_TEL                    1027
#define IDC_EDIT_TCBL                   1028
#define IDC_EDIT_HTJR                   1029
#define IDC_EDIT_JR                     1030
#define IDC_EDIT_HTBH                   1031
#define IDC_LIST_SK                     1032
#define IDC_EDIT_KFLX                   1032
#define IDC_EDIT_JR2                    1032
#define IDC_EDIT_KFMC                   1033
#define IDC_BTN_SELECTHT                1034
#define IDC_EDIT_QYR                    1034
#define IDC_STATIC_N1                   1035
#define IDC_STATIC_N2                   1036
#define IDC_STATIC_N3                   1037
#define IDC_STATIC_N4                   1038
#define IDC_EDIT_KP1                    1039
#define IDC_EDIT_KP2                    1040
#define IDC_BTN_ADDKP                   1041
#define IDC_BTN_EXPORT                  1042
#define IDC_BTN_AddTCGL                 1042
#define IDC_BTN_EXPORTXLS               1043
#define IDC_LIST_HTL                    1046
#define IDC_COMBO_GONGYI                1048
#define IDC_BTN_SELECT                  1049
#define IDC_CHECK_QYR                   1050
#define IDC_CHECK_QYDATA                1051
#define IDC_CHECK_GongYi                1052
#define IDC_CHECK_KeFu                  1053
#define IDC_COMBO_KEFU                  1054
#define IDC_BTN_CKXQ                    1055
#define IDC_BTN_NEXT                    1056
#define IDC_BTN_HTXQ                    1057
#define IDC_STATIC_TJ                   1059
#define IDC_STATIC_TJ2                  1060
#define IDC_STATIC_TJ3                  1061
#define IDC_STATIC_TJ4                  1062
#define IDC_STATIC_TJ5                  1063
#define IDC_BTN_ADDSF                   1064
#define IDC_EDIT_YJJR                   1065
#define IDC_EDIT_TJ                     1066
#define IDC_EDIT_YJSJ                   1067
#define IDC_BTN_ADDSK                   1067
#define IDC_STATIC_TJ6                  1068
#define IDC_BTN_ADDFK                   1068
#define IDC_COMBO1                      1070
#define IDC_BTN_JRDS                    1072
#define IDC_EDIT_DSJR                   1073
#define IDC_EDIT_WKPMONEY               1074
#define IDC_EDIT_YKPMONEY               1075
#define IDC_EDIT_YIKPMONEY              1076
#define IDC_BTN_JBXX                    1078
#define IDC_BTN_HTGL                    1079
#define IDC_BTNWLGL                     1080
#define IDC_BTN_KPGL                    1081
#define IDC_BTN_BKF                     1081
#define IDC_BTN_TCGL                    1082
#define IDC_BTN_BGYS                    1082
#define IDC_BTN_YJXX                    1083
#define IDC_BTN_BQYR                    1083
#define IDC_STATIC_TTEXT                1084
#define IDC_BTN_HTSELECT                1085
#define IDC_BTN_Backup                  1085
#define IDC_BTN_HTDelete                1086
#define IDC_BTN_Restore                 1086
#define IDC_EDIT_NIANDU                 1090
#define IDC_LIST_HT                     1091
#define IDC_LIST_HT2                    1092
#define IDC_BTN_ADDTCMC                 1093
#define IDC_BTN_MCSELECT                1094
#define IDC_BTN_SETBL                   1095
#define IDC_BTN_HTADDTC                 1096
#define IDC_LIST_TCMC                   1098
#define IDC_LIST_HKMC                   1099
#define IDM_QYR_BASE                    32771
#define IDM_KEFU_BASE                   32772
#define IDM_GONGYI_BASE                 32773
#define IDM_YJGN                        32774
#define IDM_ADDKP                       32775
#define IDM_KPCX                        32776
#define IDM_SYSSETM                     32777
#define IDM_ADDHTM                      32778
#define IDM_SELECTHT                    32779
#define IDM_ADDSK                       32780
#define IDM_ADDFK                       32781
#define IDM_MDELHT                      32782
#define IDM_TCGL_ADD                    32783
#define ID_MENUITEM32784                32784
#define IDM_DATABACKUP                  32786
#define IDM_DATARES                     32787
#define IDM_TCGLAddByHT                 32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
